### ISSUE TITLE
Question: Error 500 when deploying to Heroku

### ISSUE THREAD

**Issue by Winterflower** [birdsarah/bokeh-server-heroku#1]
Hello!
I am a newbie bokeh and heroku user.
I cloned this repo and followed the instructions to deploy to Heroku (but without the redis bit).
When I try to view the app, I get an Error 500. 
The heroku logs are a bit confusing, but I was able to extract this 
bit

2015-04-01T18:56:19.051354+00:00 app[web.1]:   File "/app/.heroku/miniconda/lib/python2.7/site-packages/redis/client.py", line 863, in get
2015-04-01T18:56:19.051352+00:00 app[web.1]:     data = self.redisconn.get(key)
2015-04-01T18:56:19.051363+00:00 app[web.1]:     connection = self.make_connection()

It seems that the app is trying to connect to redit even though I did not user Redis to deploy. 
Any help/tips appreciated.

**Comment by birdsarah** [comment]
Hi! I'm so sorry, I just noticed this. 

Yes, this assumes redis. 

If you would like to try without redis, you can comment out https://github.com/birdsarah/bokeh-server-heroku/blob/master/config.py#L7

and replace with 

```
model_backend = {'type' : 'shelve'}
```

However, that creates large files on disk and I'm not sure how well it will run on heroku. There is a free redis add on for heroku, why not try it out.

**Comment by Winterflower** [comment]
@birdsarah Thank you very much for replying! I'll give it a go!
