### ISSUE TITLE
Question: can you please give a detail description of the process on how to deploy the app locally as well as at heroku?

### ISSUE THREAD

**Issue by yabebalFantaye** [birdsarah/bokeh-server-heroku#2]
I have been trying to run your appbokeh-server-heroku in my OSX machine, but I am unable to do it.

I managed to successfully install all the necessary dependencies. I have used pip for packages that are not found in conda. The following packages can not be installed with conda
multiuserblazeserver=0.2=py27_0_gfa58b9f
python=2.7.9=2
system=5.8=2
Moreover, neither pip nor conda can install the system package, but it seems the app can work without that.

After deactivating and activating the env, I started it with foreman
foreman start

Looking at http://localhost:5000/bokeh, however, I can only see "Bokeh Documents for defaultuser logout", and nothing more.

The main problem is that I am new to web development. So I would appreciate it very much if you can answer me the following naive questions.

*) how should I access the app from the browser?
*) What is the app suppsed to show?
*) Can you update the README with more detail?

My interest is to deploy my Bokeh project at Heroku.

**Comment by birdsarah** [comment]
Hi @yabebalFantaye, it sounds like everything's working fine if you can see the standard "Bokeh Documents for defaultuser." 

If you only want to use bokeh-server locally, you probably don't want this package. You should probaby start here: http://bokeh.pydata.org/en/latest/.

Or for more detailed examples, clone the bokeh repo - https://github.com/bokeh/bokeh

Go to the examples folder and check out the example apps and how they're run: https://github.com/bokeh/bokeh/tree/master/examples/app
