### ISSUE TITLE
deploying this app at heroku keep giving me error "slug size is larger than 300MB"? 

### ISSUE THREAD

**Issue by yabebalFantaye** [birdsarah/bokeh-server-heroku#3]
How can I reduce the slug size of this application at heroku?

**Comment by birdsarah** [comment]
sorry for not replying sooner....the slug is big, but it has always deployed for me....there was one time, where i had to comment out requirements and add them slowly and then it worked...sorry to not be more help. i'll leave this open until its better sorted.
