### ISSUE TITLE
I have commented out line 7 and model_backend for 'redis', and un-commented model_backend for 'shelve', but logs still ask for redis connection

### ISSUE THREAD

**Issue by charleywan2004** [birdsarah/bokeh-server-heroku#4]
I have commented out line 7 and model_backend for 'redis', and un-commented model_backend for 'shelve', but logs still ask for redis connection. Is it possible to deploy this example to Heroku with database connection by commenting out all those related to database setup? 

import os, urlparse
redis_url = urlparse.urlparse(os.environ.get('REDISCLOUD_URL', '127.0.0.1:6397'))

ws_conn_string = "wss://%s/bokeh/sub" % (os.environ.get('HOSTNAME'))
pub_zmqaddr = "ipc:///tmp/0"
sub_zmqaddr = "ipc:///tmp/1"
# run_forwarder = True
# model_backend = {'type' : 'redis',
# 'redis_host': redis_url.hostname,
# 'redis_port' : redis_url.port,
# 'redis_password' : redis_url.password,
# 'start-redis' : False}

model_backend = {'type': 'shelve'}
secret_key = os.environ.get('BOKEH_SECRET_KEY', 'another secret key')
multi_user = False
scripts = [
    'blueprints/sliders_app_hbox.py',
    'blueprints/washmap_app.py',
]

**Comment by birdsarah** [comment]
Bokeh has had the server re-written. I would not recommend using this repo. 

Please see user guide for current server: http://bokeh.pydata.org/en/latest/docs/user_guide/server.html
